/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cliente;

import java.io.StringReader;
import java.io.StringWriter;
import javax.swing.JOptionPane;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import jdk.nashorn.internal.ir.debug.JSONWriter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;




/**
 *
 * @author Carlos J
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonConsultas = new javax.swing.JButton();
        buttonAltas = new javax.swing.JButton();
        buttonBajas = new javax.swing.JButton();
        buttonModificaciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        buttonConsultas.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonConsultas.setText("Mostrar");
        buttonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultasActionPerformed(evt);
            }
        });

        buttonAltas.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonAltas.setText("Agregar");
        buttonAltas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAltasMouseClicked(evt);
            }
        });

        buttonBajas.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonBajas.setText("Eliminar");
        buttonBajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBajasMouseClicked(evt);
            }
        });

        buttonModificaciones.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonModificaciones.setText("Modificar");
        buttonModificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonModificacionesMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(buttonModificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Mostrar
    private void buttonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultasActionPerformed
        //Conexion
        String URLConexion ="http://localhost:8080/TAP_Unidad03_Practica05/recursosDB/endpoint/productos";
        Client cliente = ClientBuilder.newClient();
        WebTarget objetivo = cliente.target(URLConexion);
        String respuesta = objetivo.request(MediaType.APPLICATION_JSON).get(String.class);
        
        //Convertir respuesta a ArrayJSON
        JSONParser parser = new JSONParser();
        JSONArray lista = new JSONArray();
        try {
            lista=(JSONArray)parser.parse(respuesta);
        } catch (ParseException ex) {
           ex.printStackTrace();
           System.out.println("Error al mostrar la lista");
        }
        
        //Imprimir
        jTextArea1.setText("\t                  PRODUCTOS\n____________________________________________________\n\n");
        for (int i = 0; i < lista.size(); i++) {
            JSONObject json = (JSONObject)lista.get(i);
            jTextArea1.append(json.toString());
            jTextArea1.append("\n");
        }
        
    }//GEN-LAST:event_buttonConsultasActionPerformed

    //Añadir
    private void buttonAltasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAltasMouseClicked
        String nuevo = JOptionPane.showInputDialog("Nombre del Producto:");
        
        String URLConexion ="http://localhost:8080/TAP_Unidad03_Practica05/recursosDB/endpoint/añadir/"+nuevo.trim();
        Client cliente = ClientBuilder.newClient();
        WebTarget objetivo = cliente.target(URLConexion);
        String respuesta = objetivo.request(MediaType.TEXT_PLAIN).get(String.class);
        
        System.out.println(respuesta);
        JOptionPane.showMessageDialog(null,"Elemento Agregado");
        this.buttonConsultasActionPerformed(null);
    }//GEN-LAST:event_buttonAltasMouseClicked

    //Eliminar
    private void buttonBajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBajasMouseClicked
        String producto =JOptionPane.showInputDialog("Nombre del produto: ");
        
        String URLConexion ="http://localhost:8080/TAP_Unidad03_Practica05/recursosDB/endpoint/eliminar/"+producto.trim();
        Client cliente = ClientBuilder.newClient();
        WebTarget objetivo = cliente.target(URLConexion);
        String respuesta = objetivo.request(MediaType.TEXT_PLAIN).get(String.class);
        
        System.out.println(respuesta);
        JOptionPane.showMessageDialog(null,"Elemento Eliminado");
        this.buttonConsultasActionPerformed(null);
    }//GEN-LAST:event_buttonBajasMouseClicked

    //Modificar
    private void buttonModificacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModificacionesMouseClicked
        String id =JOptionPane.showInputDialog("Id del producto: ");
        String producto =JOptionPane.showInputDialog("Nuevo nombre del produto: ");
//        
//        JSONObject json = new JSONObject();
//        json.put("id",Integer.parseInt(id));
//        json.put("descripcion",producto);
//        
//        String URLConexion ="http://localhost:8080/TAP_Unidad03_Practica05/recursosDB/endpoint/modificar/"
//                            +json.toJSONString();

        String URLConexion ="http://localhost:8080/TAP_Unidad03_Practica05/recursosDB/endpoint/modificar/"
                            + "%7B\"descripcion\":\""+producto+"\",\"id\":"+id+"%7D";
        Client cliente = ClientBuilder.newClient();
        WebTarget objetivo = cliente.target(URLConexion);
        String respuesta = objetivo.request(MediaType.APPLICATION_JSON).get(String.class);
        
        System.out.println(respuesta);
        JOptionPane.showMessageDialog(null,"Elemento Modificado");
        this.buttonConsultasActionPerformed(null);
    }//GEN-LAST:event_buttonModificacionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAltas;
    private javax.swing.JButton buttonBajas;
    private javax.swing.JButton buttonConsultas;
    private javax.swing.JButton buttonModificaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
