/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Practica09;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Random;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Carlos J
 */
public class Practica09 extends javax.swing.JFrame {

    /**
     * Creates new form Practica09
     */
    private JSONArray publicaciones;//Arreglo de publicaciones
    
    public Practica09() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.YELLOW);//Cambiar el color del panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTask1 = new org.edisoncor.gui.button.ButtonTask();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        comboBoxImagenes = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new org.edisoncor.gui.textField.TextFieldRectIcon();
        txtCantidad = new org.edisoncor.gui.textField.TextFieldRectIcon();
        btnGuardar = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/Imagen01.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        comboBoxImagenes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Imagen01", "Imagen02", "Imagen03", "Imagen04", "Imagen05" }));
        comboBoxImagenes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxImagenesItemStateChanged(evt);
            }
        });

        jLabel1.setText("Seleccione una imagen: ");

        jLabel2.setText("Nombre del Producto:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Cantidad:");

        btnGuardar.setText("Guardar");
        btnGuardar.setDescription("Publicacion");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboBoxImagenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxImagenesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxImagenesItemStateChanged
        switch (comboBoxImagenes.getSelectedIndex()) {
            case 0:
                    panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/Imagen01.jpg")));
                break;
            case 1:
                    panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/Imagen02.jpg")));
                break;
            case 2:
                    panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/Imagen03.jpg")));
                break;
            case 3:
                    panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/Imagen04.jpg")));
                break;
            case 4:
                    panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/Imagen05.jpg")));
                break;
            default:
                throw new AssertionError();
        }
        panelImage1.updateUI();
    }//GEN-LAST:event_comboBoxImagenesItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //Abrir el archivo
            File arv = new File("Publicaciones.json");
            if (!arv.exists()) {
                BufferedWriter escritor = new BufferedWriter(new FileWriter(arv));
                escritor.write("[]");
                escritor.close();
            }
            leer();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        JSONObject nuevoProducto = new JSONObject();
        nuevoProducto.put("Nombre",txtNombre.getText());
        nuevoProducto.put("Precio",Double.parseDouble(txtPrecio.getText()));
        nuevoProducto.put("Cantidad",Integer.parseInt(txtCantidad.getText()));
        //System.out.println(comboBoxImagenes.getSelectedItem().toString());
        nuevoProducto.put("Imagen",comboBoxImagenes.getSelectedItem().toString());
        
        JSONObject nuevoVendedor = new JSONObject();
        nuevoVendedor.put("Nombre","Alverto");
        nuevoVendedor.put("Correo","Alverto01@gmail.com");
        nuevoVendedor.put("Reputacion",9.5);
        
        JSONObject nuevaPublicacion = new JSONObject();
        nuevaPublicacion.put("Producto",nuevoProducto);
        nuevaPublicacion.put("Vendedor",nuevoVendedor);
        Random ram=new Random();
        nuevaPublicacion.put("Tipo",ram.nextInt(3));
        
        publicaciones.add(nuevaPublicacion);
        
        try {
            BufferedWriter escritor = new BufferedWriter(new FileWriter("Publicaciones.json",false));
            escritor.write(publicaciones.toJSONString());
            escritor.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"Guardado Satisfactoriamente");
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica09().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask btnGuardar;
    private org.edisoncor.gui.button.ButtonTask buttonTask1;
    private org.edisoncor.gui.comboBox.ComboBoxRound comboBoxImagenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextFieldRectIcon txtCantidad;
    private org.edisoncor.gui.textField.TextFieldRound txtNombre;
    private org.edisoncor.gui.textField.TextFieldRectIcon txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void leer() {
        try {
            BufferedReader lector=new BufferedReader(new FileReader("Publicaciones.json"));
            String cadena="";
            String dato=null;
            while ((dato=lector.readLine())!=null) {                
                cadena+=dato;
                //System.out.println(cadena);
            }
            lector.close();
            JSONParser parser = new JSONParser();
            publicaciones=(JSONArray)parser.parse(cadena);//Guardar la cadena extraida en el arrego de JSON
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
