/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.windows;


import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.UIManager;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Response;
import mdlaf.MaterialLookAndFeel;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Carlos J
 */
public class Acceso extends javax.swing.JFrame {

    private String usuario;
    
    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Acceso(String usuario) {
        initComponents();
        
        this.usuario = usuario;
        
        setLocationRelativeTo(null);
        
        labelPass.setForeground(MaterialColors.LIGHT_BLUE_400);
        
        labelError.setForeground(MaterialColors.RED_400);
        labelError.setVisible(false);
        
        buttonAcceso.setBackground(MaterialColors.LIGHT_BLUE_400);
        buttonAcceso.setForeground(Color.WHITE);
        
        MaterialUIMovement.add(buttonCambiar, MaterialColors.LIGHT_BLUE_500, 5, 1000 / 30);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        labelPass = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        buttonCambiar = new javax.swing.JButton();
        buttonAcceso = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso");

        labelTask1.setText("MySys");
        labelTask1.setDescription("Acceder");

        labelPass.setText("Contraseña");

        labelError.setText("La contraseña es incorrecta. Vuelva a intentarlo.");

        buttonCambiar.setText("Cambiar usuario");
        buttonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiarActionPerformed(evt);
            }
        });

        buttonAcceso.setText("Acceso");
        buttonAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccesoActionPerformed(evt);
            }
        });

        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(buttonCambiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAcceso)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelPass))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelError)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passField)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCambiar)
                    .addComponent(buttonAcceso))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Accesar al sistema
    private void buttonAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccesoActionPerformed
        labelError.setVisible(false);

        String urlWS = "http://localhost:8080/TAP_Unidad03_Practica06/res/service/acceso";

        try {
            Client client = ClientBuilder.newClient();
            WebTarget target = client.target(urlWS);

            Response response = target
                .queryParam("usr", usuario)
                .queryParam("pass", passField.getText())
                .request().method("POST");

            String strRespuesta = response.readEntity(String.class);

            System.out.println(strRespuesta);

            JSONParser jParser = new JSONParser();
            JSONObject json = (JSONObject) jParser.parse(strRespuesta);
            
            if(json.containsKey("id_usuario")) {
                acceso(json);
            }
            labelError.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonAccesoActionPerformed

    private void passFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonAccesoActionPerformed(null);
        }
    }//GEN-LAST:event_passFieldKeyPressed

    private void buttonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiarActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_buttonCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Material Design look and feel */
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcceso;
    private javax.swing.JButton buttonCambiar;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelPass;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables
    
    private void acceso(JSONObject usuario) {
        dispose();
        new Principal(usuario).setVisible(true);
    }
    
}
