/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.windows;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.UIManager;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Response;
import mdlaf.MaterialLookAndFeel;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Carlos J
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        labelUsr.setForeground(MaterialColors.LIGHT_BLUE_400);
        
        labelError.setForeground(MaterialColors.RED_400);
        labelError.setVisible(false);
        
        buttonSiguiente.setBackground(MaterialColors.LIGHT_BLUE_400);
        buttonSiguiente.setForeground(Color.WHITE);
        
        MaterialUIMovement.add(buttonCrear, MaterialColors.LIGHT_BLUE_500, 5, 1000 / 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSiguiente = new javax.swing.JButton();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        textFieldUsuario = new javax.swing.JTextField();
        labelUsr = new javax.swing.JLabel();
        buttonCrear = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        buttonSiguiente.setText("Siguiente");
        buttonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiguienteActionPerformed(evt);
            }
        });

        labelTask1.setText("MySys");
        labelTask1.setDescription("Acceder");

        textFieldUsuario.setToolTipText("Ingresa tu usuario");
        textFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldUsuarioKeyPressed(evt);
            }
        });

        labelUsr.setText("Usuario");

        buttonCrear.setText("Crear cuenta");
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        labelError.setText("El usuario no existe o es incorrecto. Vuelva a intentarlo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textFieldUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelUsr)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelError)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(buttonCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSiguiente)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrear)
                    .addComponent(buttonSiguiente))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiguienteActionPerformed
        labelError.setVisible(false);

        String urlWS = "http://localhost:8080/TAP_Unidad03_Practica06/res/service/users";

        try {
            Client client = ClientBuilder.newClient();
            WebTarget target = client.target(urlWS);

            Response response = target.request().method("POST");
            String strRespuesta = response.readEntity(String.class);

            System.out.println(strRespuesta);

            JSONParser jParser = new JSONParser();
            JSONArray jArray = (JSONArray) jParser.parse(strRespuesta);

            // Buscar el usuario
            for (int i = 0; i < jArray.size(); i++) {
                if(jArray.get(i).equals(textFieldUsuario.getText())) {
                    siguiente(textFieldUsuario.getText());
                    break;
                }
            }
            labelError.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonSiguienteActionPerformed

    private void textFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonSiguienteActionPerformed(null);
        }
    }//GEN-LAST:event_textFieldUsuarioKeyPressed

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        dispose();
        new CrearCuenta().setVisible(true);
    }//GEN-LAST:event_buttonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Material Design look and feel */
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCrear;
    private javax.swing.JButton buttonSiguiente;
    private javax.swing.JLabel labelError;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private javax.swing.JLabel labelUsr;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
    
    private void siguiente(String usr) {
        dispose();
        new Acceso(usr).setVisible(true);
    }
    
}
